on: push
name: Release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' 
    steps:
      - name: Install
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      
      - name: Create changelog
        id: changelog
        uses: dragonraid/changelog-emitter@v0.3.1
        with:
          github_token: ${{ github.token }}

      - name: Build
        id: build
        run: npm run build

      - name: Bump tag
        if: steps.changelog.outputs.isEmpty == 'false'
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}
          release_branches: develop
          default_bump: ${{ github.event.pull_request.title }}

      - name: Create Release With Asset
        id: release
        uses: Hs1r1us/Release-AIO@v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          release_name: ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          asset_files: './dist'
          draft: false
          prerelease: false
          commitish: ${{ steps.last_git_commit_data.outputs.hash }}
