name: 'Simple Autorelease'
description: 'Simple autorelease GitHub action'

branding:
  icon: star
  color: purple

inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  release_branch:
    description: Release branch
    required: false
    default: master
  default_bump:
    description: How to bump version? Major.Minor.Patch
    required: false
    default: patch
    
outputs:
  not_released:
    description: "Returns if new version was released"
    value: ${{ steps.changelog.outputs.isEmpty }}
  new_version:
    description: "New version tag"
    value: ${{ steps.tag.outputs.new_tag }}

runs:
  using: 'composite'
  steps:
    - name: Create changelog
      id: changelog
      uses: dragonraid/changelog-emitter@v0.3.1
      with:
        github_token: ${{ inputs.github_token }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm i

    - name: Build
      id: build
      run: npm run build

    - name: Bump tag
      if: steps.changelog.outputs.isEmpty == 'false'
      id: tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ inputs.github_token }}
        release_branches: ${{ inputs.release_branch }}
        default_bump: ${{ github.event.pull_request.title }}

    - name: Create Release With Asset
      id: release
      uses: Hs1r1us/Release-AIO@v2.0.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ steps.tag.outputs.new_tag }}
        release_name: ${{ steps.tag.outputs.new_tag }}
        body: ${{ steps.changelog.outputs.changelog }}
        asset_files: './dist'
        draft: false
        prerelease: false
        commitish: ${{ steps.last_git_commit_data.outputs.hash }}